[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Geschwindigkeit für den Seriellen Monitor
monitor_speed = 115200

; Turbo-Upload für das Flashen über USB (spart enorm viel Zeit)
upload_speed = 921600